backend:
  name: gitlab
  repo: StudentforeningenCampusSkelleftea/studentforeningen

media_folder: static/assets
public_folder: assets

collections:
  - name: suborg
    label: Sub Organization
    folder: pages/suborg
    create: true
    fields:
      - { name: type, widget: hidden, default: suborg }
      - { name: title, label: Title }
      - { name: description, label: Description, widget: markdown }
  - name: blog
    label: Posts
    folder: pages/blog
    create: true
    fields: 
      - { name: type, widget: hidden, default: blog }
      - { name: path, label: Path }
      - { name: date, label: Date, widget: date }
      - { name: title, label: Title }
      - { name: body, label: Body, widget: markdown }