backend:
  name: github
  repo: StudentforeningenCampusSkelleftea/studentforeningen

media_folder: static/assets
public_folder: assets

collections:
  - name: suborg
    label: Sub Organization
    folder: pages/suborg
    create: true
    fields:
      - { name: type, widget: hidden, default: suborg }
      - { name: title, label: Name }
      - { name: body, label: Description, widget: markdown }